[tools]
lefthook = "latest"

[env]
_.file = '.env'

[tasks.lint]
description = 'Format and lint with clippy'
env = { RUST_BACKTRACE = '1' }
run = 'cargo fmt && cargo clippy'
alias = 'l'

[tasks.build]
description = 'Build the project'
run = 'docker build -t trunk-processor:latest .'
alias = 'b'

[tasks.db]
description = 'Clean and run database for development'
run = [
    'docker compose down',
    'rm -r ./pgdata',
    'docker compose up -d db',
    'sleep 3',
    'diesel migration run'
]