services:
  trunk-processor:
    image: trunk-processor:latest
    container_name: trunk-processor
    env_file:
      - .env
    ports:
      - "3001:3000"
    dns:
      - 10.0.10.1
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trunk-processor
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
